# Generated by Django 5.0.6 on 2024-07-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('rdesc', models.TextField()),
                ('rimage', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
